spring.application.name=api

# Configuracoes do Banco de Dados PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:8081/eventos_db
spring.datasource.username=postgres
spring.datasource.password=teus123
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
aws.region=us-east-1
aws.bucket.name=eventotec-Imagem